# Generated by Django 2.2.5 on 2019-09-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('notice', '공지사항'), ('envs', '표준환경'), ('lecture', '기초강의'), ('people', '교수진'), ('etc', '기타')], default='etc', max_length=10)),
                ('body', models.TextField()),
            ],
        ),
    ]
