# Generated by Django 2.2.5 on 2019-09-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190925_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('notice', '공지사항'), ('envs', '표준환경'), ('lecture', '기초강의'), ('people', '교수진'), ('etc', '기타')], default='분류없음', max_length=30),
        ),
    ]
